name: Autograder

on: [workflow_dispatch]

jobs:
  build:
    runs-on: furrysalamander/icarus:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ${{ github.workspace }}/test.sh