name: Autograder

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: furrysalamander/icarus:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python3 grader/autograde.py
      - run: cat report.md >> $GITHUB_STEP_SUMMARY
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: vcd-files
      #     path: 
    
      