name: Autograder

on: [workflow_dispatch]

jobs:
  build:
    container:
      image: furrysalamander/icarus:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python3 ${{ github.workspace }}/grader/autograde.py
      