name: Autograder

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: furrysalamander/icarus:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls
      - run: python3 grader/autograde.py
      